name: Test build and deploy

on:
  push:
    branches: [main]
    paths:
      - 'FakeRetailDB/**'
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build .dacpac
        run: dotnet build FakeRetailDB/FakeRetailDB.sqlproj --configuration Release

      - name: Publish to SQL Server
        run: |
          sqlpackage /Action:Publish \
            /SourceFile:"FakeRetailDB/bin/Release/FakeRetailDB.dacpac" \
            /TargetServerName:"Winston\SQLEXPRESS01" \
            /TargetDatabaseName:"FakeRetailDB" \
            /p:BlockOnPossibleDataLoss=false

