name: Validate Database Build

on:
  pull_request:
    branches: [main]
    paths:
      - 'FakeRetailDB/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build .dacpac
        run: dotnet build FakeRetailDB/FakeRetailDB.sqlproj --configuration Release